### PR TITLE
Updated for travisCI job

### PR DESCRIPTION
**Pull request by frosario**

### CODE REVIEW

**Comment by aslagle** [comment]
I'd really like to be able to leave the tests in packages and run them that way. Is it necessary to make them app-level tests, and if so can we move them as part of the travis build instead of in the repo?

**Comment by frosario** [comment]
Just updated branch with script to copy files up the the app level (for the travis build) @aslagle

**Comment by aslagle** [comment]
Cool that should work. Are the original package groupings reflected in the output from travis at all?

**Comment by frosario** [comment]
Not exactly. You get an indication of what test passed with output that looks like:
<pre></code>PASSED jasmine-client-unit : accountsHeaderButtons:Accounts => Accounts accountsHeaderButtons sets up the template
PASSED jasmine-client-unit : accountsHeaderButtons:Accounts => Accounts accountsHeaderButtons renders a sign-out link</code></pre>

Full log here:
https://travis-ci.org/ecohealthalliance/mantle

**Comment by aslagle** [comment]
That's ok as long as we include the package in the test names. Let's try breaking a test to see how it looks?

**Comment by frosario** [comment]
Pushed commit `a60efdfb24f64904e852436d0fb72aae38b0a1e6`

This caused a test to fail. Full output here:
https://travis-ci.org/ecohealthalliance/mantle/builds/67258448

**Comment by aslagle** [comment]
That's not ideal - any way to hide those giant stack traces from jasmine?

**Comment by frosario** [comment]
@aslagle Please see the new output at:
https://travis-ci.org/ecohealthalliance/mantle/builds/67370755

If that works, we can revert commit `a60efdfb24f64904e852436d0fb72aae38b0a1e6` to get the tests passing again.

**Comment by aslagle** [comment]
Thanks, much better. I'm going to try out some more complex tests on this branch.

**Comment by aslagle** [comment]
I don't seem to be a member of our organization on travis-ci, even though I am on github. These last builds stalled for some reason.

**Pull request closed without merging**
